_wandb:
    value:
        cli_version: 0.23.0
        e:
            piu2tp0mkp3566e5pyxujc76s9wgunbk:
                args:
                    - --just_one
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "216160342016"
                        used: "160274223104"
                email: chiara-peppicelli@libero.it
                executable: /home/lollo/miniconda3/envs/QML/bin/python
                git:
                    commit: 4d6a0f208bc9dca4bbdc07100622b4a3e5300c3d
                    remote: https://github.com/chiarapepp/Quantum-Machine-Learning-Project.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-21352f08-1e39-14c8-46c2-3353c5665118
                host: lollo-MS-7E26
                memory:
                    total: "32793133056"
                os: Linux-6.14.0-34-generic-x86_64-with-glibc2.39
                program: -m src.train
                python: CPython 3.11.14
                root: /home/lollo/Documenti/vscode/Quantum-Machine-Learning-Project
                startedAt: "2025-11-20T16:59:44.095742Z"
                writerId: piu2tp0mkp3566e5pyxujc76s9wgunbk
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.0
            "10":
                - 20
            "12": 0.23.0
            "13": linux-x86_64
arch:
    value: simple
batch_size:
    value: 32
epochs:
    value: 8
hinge_margin:
    value: 1
lr:
    value: 0.01
momentum:
    value: 0
n_layers:
    value: 2
n_qubits:
    value: 8
optimizer:
    value: adam
output_dir:
    value: results/checkpoints
shots:
    value: 200
use_cuda:
    value: false
use_shots:
    value: false
wandb_project:
    value: naduqnn_repro
weight_decay:
    value: 0
